name: Build Docker Container & Push to Docker Hub

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: rjraju
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
      - name: Build container image
        working-directory: ./web
        run: |
          docker build -f Dockerfile \
            -t rjraju/django-k8s-web:latest \
            -t rjraju/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image to Docker Hub
        run: |
          docker push rjraju/django-k8s-web:latest
          docker push rjraju/django-k8s-web:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
